Gum 1897 remove winston from logger
gumbandapp/gumband-public-shared-lib pull request #5
Opened 2024-11-07 21:13 UTC by BennEntterprise

My initial pass at yanking out winston from the gumband-public-shared-lib. I still need to test this in the FEv2 to ensure that it is backwards compatible. I'm also not thrilled with commenting out all the tests because that to me means we've lost functionality, going to mull it over and see what/how these can be brought back in but perhaps they weren't needed all along.

2024-11-12 17:10 UTC, BennEntterprise commented on src/constants/GbWinstonLogginConstants.ts
> +import { LOG_LEVELS } from './LogLevels';
I included this because I figured

2024-11-12 17:11 UTC, BennEntterprise commented on src/constants/GbWinstonLogginConstants.ts
> +};
This whole file was included because I thought it might be nice to have a standard config that we ship with the lib so that in our backend services we can use these constants to create the logger we want to inject (configured winston)

2024-11-13 18:12 UTC, bracketbear requested changes
Great work! Really appreciate you taking this on, sir. I tested this on the FE and it works. 😎

I added a couple of comments about switching `any` to `unknown` that I think we should address, but everything else were just nits about comments.

2024-11-13 18:12 UTC, bracketbear commented on src/utils/gbLogger.ts
>      name?: string;
Down the file, I talk about yanking the jsdoc constructor comments out from the class below. Here's how I'd modify the constructor interface to include the comments:

```typescript
 /** Options for the logger */
 export type GbLoggerConstructorObjectOpts = {
      /** Hide the UTC timestamp? */
      hideUtc?: boolean
      /** The log level */
      level?: LogLevelType;
      /** The name of the logger */
      name?: string;
      /** The timezone */
      tz?: string; // A timezone string, when omitted timestamps will be UTC
      /** The injected logger instance */
      logger?: LoggerInterface; // Injected logger instance
 };
 ```

2024-11-21 19:21 UTC, BennEntterprise commented on src/constants/GbWinstonLogginConstants.ts
> +};
added this

2024-11-21 19:22 UTC, BennEntterprise commented on src/constants/GbWinstonLogginConstants.ts
> +const transports: any[] = []; // We don't know what transports will be added
_technically_ it's a winston transport, or a transport that complies with that interface. However, to correctly type it, we'd need the `winston` library. So I did update this to be `unknown`

2024-11-21 19:26 UTC, BennEntterprise commented on src/utils/gbLogger.ts
> +     * @param {any} message - The message to log
updated

2024-11-21 19:26 UTC, BennEntterprise commented on src/utils/gbLogger.ts
> +     */
I did pull them out and put `/* eslint-disable-next-line require-jsdoc */` for this set

2024-11-21 19:27 UTC, BennEntterprise commented on src/utils/gbLogger.ts
>      name?: string;
yupp. Took that advice

2024-11-22 20:14 UTC, bracketbear approved these changes
LGTM! Really appreciate you jumping on this

2024-12-02 16:04 UTC, echmielewski approved these changes

2024-12-11 17:07 UTC, merged